config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :articles do
    resources :comments
  end

  root "articles#index"
  match '/about', 		 to: 'about#index', 	via:'get'
  match '/contacts',     to: 'contacts#new',    via: 'get'
  resources "contacts",  only: [:new, :create]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true,
						length: { minimum: 5}

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  def should_generate_new_friendly_id?
  	new_record?
  end


end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => ENV['GMAIL_USERNAME'],
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def index
		@articles = Article.all.order('updated_at DESC')
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	def show
		@article = Article.find(params[:id])
		if request.path != article_path(@article)
			redirect_to @article, status: :moved_permanently
		end
	end

	private
		def article_params
			params.require(:article).permit(:title, :text);
		end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	#returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Eating, Deadlifting and Starting"
		if page_title.empty?
			base_title
		else
			"#{page_title}"
		end
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/about/index.html.erb
<% provide(:title, "The United States Greatest Youth?") %>
<section class="row">
	<div class="clientblock-top1">
		<%= image_tag("customer-img-1.jpg", :class => "img-padding", :alt => "EV's handsome headshot") %>
	    <p><strong>EV</strong><br>
	      Future better looking Mr. Zuckerburg</p>
	</div>
	<div class="testblock">
		EV recently graduated from college where he was able to hone his Software Design skills while also having time to drastically improve his deadlift.  He is currently a co-founder of his own company and has vivid dreams of making it rich, his backup plans include being a professional athlete, or, a male model.  
	</div>

	<div class="clientblock"> 
		<%= image_tag("customer-img-2.jpg", :class => "img-padding", :alt => "Kay's gorgeous face") %>
	    <p><strong>Kay</strong> <br>
	      Future CEO of Kay's Big Ass Sushi</p>
	</div>
	<div class="testblock">
	 	Kay, while still in college, is an entrepreneur at heart and finds meaning in bringing concepts and ideas to life. He spends his free time deadlifting heavy objects and creating (and then eating) new sushi concepts for his future restaurant.  Kay loves to make his own rules and always tries to disrupt the status quo.  Possibly the only thing he likes more than deadlifting is being an entrepreneur.  </div>
	</div>
</section>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/index.html.erb
<% provide(:title, 'Eating, Deadlifting and Starting Up') %>
<% @articles.each do |article| %>
<h2> <%= article.title %> </h2>
<p> <%= truncate(article.text, :length => 140, :separator => ' ', :escape => false) %> </p>
<table>
<tr>
  <td> <%= link_to 'Continue Reading', article_path(article) %> </td>
</tr>
</table>
<% end %>
      

app/views/articles/new.html.erb
<h1> New Article </h1>
<%= render 'form' %>
<%= link_to 'Back', root_path %>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>
 
<p>
  <%= @article.text.html_safe %>
</p>
 
<%= link_to 'Back to Articles', root_path %>

<%= content_tag :div, '', :class => "fb-comments", "data-href" => request.original_url, "data-numposts" => "5", "data-width" => "100%", "data-colorscheme" => "light" %>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div align="center">
        <%= link_to "Return to home page", root_path %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<% provide(:title, 'Questions, comments, concerns?') %>
<div align="left">
  <h3>Send Us A Message!</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true, wrapper_html: { class: 'special-label' } %>
    <%= f.input :email, :required => true, wrapper_html: { class: 'special-label' }  %>
    <%= f.input :message, :as => :text, :required => true, wrapper_html: { class: 'special-label' }  %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div class = "text-center">
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer Starts -->
<section class=" breath sub-footer">
	<div class="col-md-12 footerlinks"> 
	  	<%= link_to "Home", root_path %>
	  	<%= link_to "About", about_path %>
		<%= link_to "Contact", contacts_path %>
	 	<p>&copy; Just Two Startup Guys</p>
	</div>
</section>
<!-- // End Footer and Logos --> 

<!-- //Google analytics footer code, workaround for rails 4 -->

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52529368-1', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');

</script>

app/views/layouts/_navbar.html.erb
<div class="header clearfix">
	<input type="checkbox" id="toggle" />
	<div>
		<label for="toggle" class="toggle" onclick></label>
		<ul class="menu">
			<li><%= link_to "HOME", root_path %></li>
			<li><%= link_to "ABOUT", about_path %></li>
			<li><%= link_to "CONTACT", contacts_path %></li>	
		</ul>
	</div> <!-- End of Navigation -->
</div>


    

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="js/html5shiv.js"></script>
  <script src="js/respond.min.js"></script>
<![endif]
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
	    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	    <meta name="description" content="Responsive blog about the adventures of two entrepreneurs in sunny Cleveland ">
	    <meta name="keywords" content="Blog blogging blogger entrepreneur cleveland startup blog sites adventure entrepreneurship ideas ">
	    <meta name="author" content="Eric">
	    <%= render 'layouts/shim' %>
	    <title> Eating, Deadlifting, and Starting Up</title>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>

	</head>
	<body>
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
		<div>
			<%= render 'layouts/navbar' %>
			<div id="container">
  				<div class="containerEV" id="explore"> 
    				<div class="section-title one-col-main-paige one-col box-full first">
    					<div class = "content-wrapper text-center">
    						<h2> <%= full_title(yield(:title)) %></h2>
    					</div>
    				
      					<div class="content-wrapper">
        					<div class="text-center">
								<p class = "notice"><%= notice %></p>
								<p class = "notice"><%= alert %></p>
							</div>
							<%= yield %>
						</div>
					</div>
				</div>
			</div>
		</div>
		<%= render 'layouts/footer' %>
	</body>
</html>